### ISSUE TITLE
Executables don't terminate when `ign launch` is terminated

### ISSUE THREAD

**Issue by azeey** [ignitionrobotics/ign-launch#149]
## Environment
* OS Version: Ubuntu 20.04 
* Source or binary build: both, `ign-launch5`
    
## Description
* Expected behavior: Every executable in a launch file to be terminated when `ign launch` is terminated with ctrl-c
* Actual behavior: In some cases, `ign launch` terminates, but the executables continue running.

## Steps to reproduce
Here's a small launch file that reproduces the issue. Interestingly, if the loaded world doesn't contain the Sensors system, the issue goes away. The issue also goes away if the `GazeboFactory` plugin is removed from the launch file.

```xml
<?xml version="1.0" ?>
<ignition version='1.0'>

  <plugin name="ignition::launch::GazeboServer" filename="ignition-launch-gazebo">
    <world_file>sky.sdf</world_file> <!-- The issue goes away if the world file is replaced with empty.sdf-->
  </plugin>

  <plugin name="ignition::launch::GazeboFactory" filename="ignition-launch-gazebo-factory"> <!-- or this plugin is removed -->
    <sdf version='1.6'>
      <include>
        <uri>
          https://fuel.ignitionrobotics.org/1.0/OpenRobotics/models/Cardboard box
        </uri>
      </include>
    </sdf>
  </plugin>

  <executable name='gazebo-client'>
    <command>ign gazebo -g</command>
  </executable>
</ignition>

```

**Comment by mjcarroll** [comment]
> Interestingly, if the loaded world doesn't contain the Sensors system, the issue goes away.

Sensors system does have background threads that may not be spun down correctly.
