### ISSUE TITLE
Should example launch .ign files be installed?

### ISSUE THREAD

**Issue by osrf-migration** [ignitionrobotics/ign-launch#2]
**Original report ([archived issue](https://osrf-migration.github.io/ignition-gh-pages/#!/ignitionrobotics/ign-launch/issues/2)) by Steve Peters (Bitbucket: [Steven Peters](https://bitbucket.org/%7B2ccfed09-18b8-4921-8d58-15ef01092802%7D/), GitHub: [scpeters](https://github.com/scpeters)).**

----------------------------------------
There are a few `.ign` files in the `examples` folder. There is a CMakeLists.txt in that folder that looks like it wants to install them, but it is not being invoked.

* https://github.com/ignitionrobotics/ign-launch/blob/422bebc78f0ba4c1246e97d4d5edcf9ab450ca5b/examples/gazebo.ign
* https://github.com/ignitionrobotics/ign-launch/blob/422bebc78f0ba4c1246e97d4d5edcf9ab450ca5b/examples/CMakeLists.txt

Are these files supposed to be installed?

**Comment by chapulina** [comment]
I can do `ign launch gazebo.ign`, so I believe this is done.
