### ISSUE TITLE
Tutorials page is not foud

### ISSUE THREAD

**Issue by osrf-migration** [ignitionrobotics/ign-launch#8]
**Original report ([archived issue](https://osrf-migration.github.io/ignition-gh-pages/#!/ignitionrobotics/ign-launch/issues/8)) by mohamed sayed (Bitbucket: [Mohamed Ahmed](https://bitbucket.org/%7B13e5d7b7-a702-4d05-9522-7586de922568%7D/)).**

----------------------------------------
![](https://osrf-migration.github.io/ignition-gh-pages/data/bitbucket.org/repo/ngEao5e/images/2675720297-image.png)
[https://ignitionrobotics.org/api/launch/2.0/index.html](https://ignitionrobotics.org/api/launch/2.0/index.html)

**Comment by nkoenig** [comment]
I'll add a tutorial, and fix the 404.

**Comment by chapulina** [comment]
https://github.com/ignitionrobotics/ign-launch/pull/48
