### ISSUE TITLE
IGN_LAUNCH_CONFIG_PATH could accept path lists

### ISSUE THREAD

**Issue by peci1** [ignitionrobotics/ign-launch#92]
## Desired behavior
ign launch should try to prepend all colon-separated paths from IGN_LAUNCH_CONFIG_PATH when searching for a launch file to launch. Currently, this variable can contain only a single path.

## Alternatives considered
All alternatives for combining multiple launch packages are bad.

## Implementation suggestion
Shouldn't be difficult, but before submitting a PR, I wanted to know whether this feature would be desired/welcome.

**Comment by chapulina** [comment]
Sounds like a good idea to me :+1:

**Comment by peci1** [comment]
Fixed by #93.
